// System component relationship data
const graphData = {
    nodes: [
        // Large spheres (2)
        { id: "simulation", name: "DLW Simulation Module", group: "simulation", category: "module", size: 40, description: "Direct Laser Writing simulation function module", sphereSize: "large", sphereType: "simulation" },
        { id: "opc", name: "OPC Optimization Module", group: "simulation", category: "module", size: 40, description: "Optical Proximity Correction optimization function module", sphereSize: "large", sphereType: "opc" },
        
        // Medium spheres (3)
        { id: "3d_editor", name: "Height Profile Generator", group: "analysis", category: "application", size: 30, description: "Interactive editing and visualization tool for 3D models, supporting point cloud operations and shape creation", sphereSize: "medium", sphereType: "coordinates" },
        { id: "customer_service", name: "Customer Service System", group: "service", category: "service", size: 30, description: "User support and problem-solving system", sphereSize: "medium", sphereType: "app_service" },
        { id: "cc3_curve", name: "CC3 Curve Generator", group: "auxiliary", category: "tool", size: 30, description: "Tool for comparing and generating CC3 curves", sphereSize: "medium", sphereType: "cc_optimization" },
        
        // Small spheres (tools and other components)
        { id: "main_app", name: "Main Application", group: "core", category: "application", size: 22, description: "Core interface of DLW application providing DLW simulation, OPC optimization and mask generation", sphereSize: "small", sphereType: "tools" },
        { id: "pydlw", name: "PYDLW Core Library", group: "core", category: "library", size: 22, description: "Provides core algorithm implementation for DLW simulation, including mask generation and dose calculation", sphereSize: "small", sphereType: "tools" },
        { id: "shape_analysis", name: "Shape Analysis", group: "analysis", category: "application", size: 20, description: "Point cloud analysis, surface fitting and geometric property analysis tools", sphereSize: "small", sphereType: "tools" },
        { id: "shape_designer", name: "Shape Designer", group: "analysis", category: "application", size: 18, description: "Professional shape design tool supporting various geometric shape creation", sphereSize: "small", sphereType: "tools" },
        { id: "data_converter", name: "Data Converter", group: "auxiliary", category: "tool", size: 18, description: "Contrast curve and height file data conversion tool", sphereSize: "small", sphereType: "tools" },
        { id: "cc_converter", name: "CC Curve Converter", group: "auxiliary", category: "tool", size: 15, description: "Tool specifically for converting contrast curve data", sphereSize: "small", sphereType: "tools" },
        { id: "height_converter", name: "Height File Converter", group: "auxiliary", category: "tool", size: 15, description: "Tool specifically for converting height file data", sphereSize: "small", sphereType: "tools" },
        { id: "dlw_chat", name: "DLW Chat Assistant", group: "ai", category: "ai", size: 18, description: "Built-in AI assistant providing technical support", sphereSize: "small", sphereType: "tools" },
        { id: "hunyuan_chat", name: "Hunyuan LLM", group: "ai", category: "ai", size: 16, description: "Advanced AI assistant based on Hunyuan large language model", sphereSize: "small", sphereType: "tools" },
        { id: "opc_progress", name: "OPC Progress Window", group: "simulation", category: "interface", size: 15, description: "OPC processing progress monitoring interface", sphereSize: "small", sphereType: "tools" },
        { id: "input_files", name: "Input Files", group: "auxiliary", category: "data", size: 15, description: "Input data files processed by the system, including masks, contrast curves, etc.", sphereSize: "small", sphereType: "tools" },
        { id: "export_files", name: "Export Files", group: "auxiliary", category: "data", size: 15, description: "Output data files generated by the system, including optimized masks, shape analysis results, etc.", sphereSize: "small", sphereType: "tools" },
        { id: "dose_export", name: "Dose Export Tool", group: "auxiliary", category: "tool", size: 15, description: "Tool for exporting dose data in CC2 format", sphereSize: "small", sphereType: "tools" },
        { id: "deepseek_chat", name: "DeepSeek Chat", group: "ai", category: "ai", size: 17, description: "Advanced LLM chat interface based on DeepSeek model for technical consultations", sphereSize: "small", sphereType: "tools" },
        { id: "tiktoken_service", name: "Tokenization Service", group: "ai", category: "ai", size: 14, description: "Token counting and preprocessing service for AI text models", sphereSize: "small", sphereType: "tools" },
        { id: "ai_knowledge_base", name: "AI Knowledge Base", group: "ai", category: "ai", size: 16, description: "Domain-specific knowledge base for AI assistants", sphereSize: "small", sphereType: "tools" },
        { id: "app_launcher", name: "App Launcher", group: "core", category: "application", size: 18, description: "Central application launcher for all DLW tools", sphereSize: "small", sphereType: "tools" },
        { id: "dlw_launch", name: "DLW Launcher Script", group: "core", category: "tool", size: 14, description: "Script for launching DLW applications with proper environment", sphereSize: "small", sphereType: "tools" },
        { id: "3d_visualization", name: "3D Visualization", group: "analysis", category: "module", size: 18, description: "WebGL-based visualization engine for 3D data", sphereSize: "small", sphereType: "tools" },
        { id: "dashboard", name: "System Dashboard", group: "auxiliary", category: "interface", size: 16, description: "Monitoring dashboard for system performance and usage statistics", sphereSize: "small", sphereType: "tools" },
        { id: "shape_prediction", name: "Shape Predictor", group: "ai", category: "ai", size: 16, description: "ML model for predicting optimal shapes based on input parameters", sphereSize: "small", sphereType: "tools" },
        { id: "parameter_optimizer", name: "Parameter Optimizer", group: "ai", category: "ai", size: 17, description: "Neural network-based parameter optimization for DLW process", sphereSize: "small", sphereType: "tools" },
        { id: "error_reporter", name: "Error Reporter", group: "service", category: "tool", size: 14, description: "Automated error reporting and diagnostic tool", sphereSize: "small", sphereType: "tools" },
        { id: "system_monitor", name: "System Monitor", group: "auxiliary", category: "tool", size: 15, description: "Real-time system resource monitoring tool", sphereSize: "small", sphereType: "tools" },
        { id: "cc_ai_assistant", name: "CC AI Assistant", group: "ai", category: "ai", size: 16, description: "AI assistant specialized for contrast curve analysis and optimization", sphereSize: "small", sphereType: "tools" },
        { id: "mask_generator", name: "AI Mask Generator", group: "ai", category: "ai", size: 18, description: "Neural network-based mask generation from shape specifications", sphereSize: "small", sphereType: "tools" },
        { id: "laser_calibration", name: "Laser Calibration AI", group: "ai", category: "ai", size: 17, description: "AI-based laser calibration and adjustment system", sphereSize: "small", sphereType: "tools" },
        { id: "simulation_predictor", name: "Simulation Predictor", group: "ai", category: "ai", size: 17, description: "AI model for predicting simulation outcomes before full processing", sphereSize: "small", sphereType: "tools" },
        { id: "photoresist_db", name: "Photoresist Database", group: "core", category: "data", size: 16, description: "Database of photoresist properties and parameters", sphereSize: "small", sphereType: "tools" },
        { id: "laser_controller", name: "Laser Controller", group: "core", category: "hardware", size: 18, description: "Hardware interface for controlling laser systems", sphereSize: "small", sphereType: "tools" },
        { id: "lithography_simulator", name: "Lithography Simulator", group: "simulation", category: "module", size: 20, description: "Detailed simulator for lithography processes and outcomes", sphereSize: "small", sphereType: "tools" },
        { id: "3d_coordinate_height", name: "3D Coordinate Height Profile", group: "analysis", category: "module", size: 19, description: "Tool for generating and visualizing 3D height maps and coordinates", sphereSize: "small", sphereType: "tools" },
        { id: "tensor2tensor", name: "Tensor2Tensor Library", group: "ai", category: "library", size: 16, description: "Machine learning library for neural machine translation and other tasks", sphereSize: "small", sphereType: "tools" }
    ],
    links: [
        // 大球之间的中心连接
        { source: "simulation", target: "opc", value: 15, description: "Core simulation and optimization pipeline" },
        
        // 确保所有中球都与OPC大球连接
        { source: "opc", target: "3d_editor", value: 10, description: "OPC data for 3D visualization and editing" },
        { source: "opc", target: "customer_service", value: 9, description: "OPC technical support interface" },
        { source: "opc", target: "cc3_curve", value: 11, description: "OPC data for curve optimization" },
        
        // 中球与模拟大球的连接
        { source: "simulation", target: "3d_editor", value: 10, description: "Simulation data for 3D editing" },
        { source: "simulation", target: "customer_service", value: 8, description: "Simulation technical support" },
        { source: "simulation", target: "cc3_curve", value: 9, description: "Simulation output for curve analysis" },
        
        // Core application relationships - primary structure
        { source: "main_app", target: "pydlw", value: 12, description: "Core dependency" },
        { source: "main_app", target: "simulation", value: 10, description: "Feature integration" },
        { source: "main_app", target: "opc", value: 10, description: "Feature integration" },
        { source: "main_app", target: "3d_editor", value: 8, description: "Integrated tool" },
        { source: "main_app", target: "shape_analysis", value: 7, description: "Analysis integration" },
        { source: "main_app", target: "customer_service", value: 5, description: "Support integration" },
        { source: "main_app", target: "app_launcher", value: 9, description: "Launch dependency" },
        
        // 3D editing and analysis relationships
        { source: "3d_editor", target: "shape_analysis", value: 9, description: "Shared analysis" },
        { source: "3d_editor", target: "shape_designer", value: 8, description: "Design integration" },
        { source: "shape_analysis", target: "export_files", value: 6, description: "Analysis output" },
        { source: "shape_designer", target: "3d_editor", value: 7, description: "Shape output" },
        { source: "3d_editor", target: "3d_visualization", value: 9, description: "Visualization engine" },
        { source: "shape_analysis", target: "shape_prediction", value: 6, description: "ML prediction" },
        
        // Simulation feature relationships - core functionality
        { source: "simulation", target: "pydlw", value: 11, description: "Algorithm implementation" },
        { source: "opc", target: "pydlw", value: 11, description: "Algorithm implementation" },
        { source: "opc", target: "opc_progress", value: 7, description: "Progress monitoring" },
        { source: "simulation", target: "export_files", value: 6, description: "Simulation output" },
        { source: "opc", target: "export_files", value: 6, description: "Optimization output" },
        { source: "simulation", target: "parameter_optimizer", value: 8, description: "Parameter optimization" },
        
        // Data conversion relationships
        { source: "data_converter", target: "cc_converter", value: 8, description: "Component relationship" },
        { source: "data_converter", target: "height_converter", value: 8, description: "Component relationship" },
        { source: "cc_converter", target: "input_files", value: 5, description: "Data input" },
        { source: "height_converter", target: "input_files", value: 5, description: "Data input" },
        { source: "cc_converter", target: "export_files", value: 5, description: "Data output" },
        { source: "height_converter", target: "export_files", value: 5, description: "Data output" },
        
        // Service system relationships
        { source: "customer_service", target: "dlw_chat", value: 7, description: "Integrated assistant" },
        { source: "customer_service", target: "hunyuan_chat", value: 6, description: "Integrated AI" },
        { source: "dlw_chat", target: "hunyuan_chat", value: 4, description: "AI integration" },
        { source: "customer_service", target: "error_reporter", value: 6, description: "Error handling" },
        { source: "customer_service", target: "deepseek_chat", value: 7, description: "Advanced AI support" },
        { source: "deepseek_chat", target: "tiktoken_service", value: 5, description: "Token processing" },
        { source: "hunyuan_chat", target: "tiktoken_service", value: 5, description: "Token processing" },
        { source: "dlw_chat", target: "ai_knowledge_base", value: 8, description: "Domain knowledge" },
        { source: "deepseek_chat", target: "ai_knowledge_base", value: 8, description: "Domain knowledge" },
        { source: "hunyuan_chat", target: "ai_knowledge_base", value: 7, description: "Domain knowledge" },
        
        // File tool relationships
        { source: "cc3_curve", target: "export_files", value: 5, description: "Curve output" },
        { source: "dose_export", target: "export_files", value: 5, description: "Dose data output" },
        { source: "input_files", target: "main_app", value: 7, description: "Application input" },
        { source: "input_files", target: "simulation", value: 8, description: "Simulation input" },
        { source: "input_files", target: "opc", value: 8, description: "Optimization input" },
        
        // Cross-module relationships
        { source: "main_app", target: "data_converter", value: 5, description: "Data processing" },
        { source: "main_app", target: "cc3_curve", value: 4, description: "Curve generation" },
        { source: "main_app", target: "dose_export", value: 4, description: "Dose output" },
        { source: "opc", target: "data_converter", value: 3, description: "Data conversion" },
        { source: "3d_editor", target: "export_files", value: 5, description: "3D model output" },
        { source: "shape_designer", target: "export_files", value: 5, description: "Shape output" },
        
        // Auxiliary application relationships
        { source: "cc3_curve", target: "cc_converter", value: 4, description: "Data processing" },
        { source: "dose_export", target: "simulation", value: 4, description: "Simulation output" },
        { source: "data_converter", target: "main_app", value: 3, description: "Data provision" },
        { source: "data_converter", target: "3d_editor", value: 3, description: "3D data input" },
        
        // Additional core workflow links
        { source: "pydlw", target: "simulation", value: 9, description: "Simulation algorithms" },
        { source: "pydlw", target: "opc", value: 9, description: "Optimization algorithms" },
        { source: "shape_analysis", target: "shape_designer", value: 6, description: "Analysis feedback" },
        { source: "export_files", target: "shape_analysis", value: 4, description: "Analysis input" },
        
        // Launcher and integration relationships
        { source: "app_launcher", target: "dlw_launch", value: 8, description: "Launch script" },
        { source: "app_launcher", target: "3d_editor", value: 6, description: "App launching" },
        { source: "app_launcher", target: "shape_designer", value: 6, description: "App launching" },
        { source: "app_launcher", target: "data_converter", value: 5, description: "App launching" },
        { source: "app_launcher", target: "system_monitor", value: 4, description: "System monitoring" },
        { source: "dlw_launch", target: "main_app", value: 7, description: "Main app launch" },
        
        // AI and ML relationships
        { source: "shape_prediction", target: "shape_analysis", value: 7, description: "Analysis input" },
        { source: "parameter_optimizer", target: "opc", value: 7, description: "OPC optimization" },
        { source: "main_app", target: "dlw_chat", value: 6, description: "Integrated support" },
        { source: "error_reporter", target: "ai_knowledge_base", value: 5, description: "Error knowledge" },
        
        // Monitoring and visualization
        { source: "system_monitor", target: "dashboard", value: 7, description: "Performance data" },
        { source: "main_app", target: "dashboard", value: 5, description: "Usage statistics" },
        { source: "3d_visualization", target: "dashboard", value: 4, description: "Visualization component" },
        { source: "3d_visualization", target: "3d_editor", value: 8, description: "Visualization engine" },
        { source: "shape_prediction", target: "3d_visualization", value: 6, description: "Prediction visualization" },
        
        // Error handling
        { source: "error_reporter", target: "customer_service", value: 7, description: "Support ticket creation" },
        { source: "main_app", target: "error_reporter", value: 6, description: "Error reporting" },
        { source: "simulation", target: "error_reporter", value: 5, description: "Simulation errors" },
        { source: "opc", target: "error_reporter", value: 5, description: "OPC errors" },
        { source: "system_monitor", target: "error_reporter", value: 6, description: "System issue detection" },
        
        // New AI tool relationships
        { source: "cc_ai_assistant", target: "cc_converter", value: 7, description: "CC data processing" },
        { source: "cc_ai_assistant", target: "ai_knowledge_base", value: 6, description: "Knowledge retrieval" },
        { source: "cc_ai_assistant", target: "cc3_curve", value: 8, description: "Curve optimization" },
        { source: "mask_generator", target: "shape_designer", value: 7, description: "Shape integration" },
        { source: "mask_generator", target: "simulation", value: 8, description: "Simulation input" },
        { source: "mask_generator", target: "shape_prediction", value: 6, description: "ML feedback" },
        { source: "laser_calibration", target: "laser_controller", value: 7, description: "Hardware control" },
        { source: "laser_calibration", target: "parameter_optimizer", value: 6, description: "Parameter tuning" },
        { source: "simulation_predictor", target: "simulation", value: 9, description: "Simulation acceleration" },
        { source: "simulation_predictor", target: "opc", value: 7, description: "OPC pre-processing" },
        { source: "main_app", target: "cc_ai_assistant", value: 5, description: "AI assistant integration" },
        { source: "main_app", target: "mask_generator", value: 6, description: "Mask creation" },
        
        // New DLW component relationships
        { source: "photoresist_db", target: "simulation", value: 8, description: "Simulation parameters" },
        { source: "photoresist_db", target: "opc", value: 7, description: "Optimization parameters" },
        { source: "photoresist_db", target: "pydlw", value: 6, description: "Core data" },
        { source: "laser_controller", target: "main_app", value: 7, description: "Hardware control" },
        { source: "laser_controller", target: "simulation", value: 6, description: "Simulation parameters" },
        { source: "lithography_simulator", target: "simulation", value: 8, description: "Enhanced simulation" },
        { source: "lithography_simulator", target: "parameter_optimizer", value: 7, description: "Parameter input" },
        { source: "lithography_simulator", target: "photoresist_db", value: 6, description: "Material properties" },
        
        // 根据项目实际关系更新的连接
        // 启动器和应用程序关系
        { source: "dlw_launch", target: "app_launcher", value: 10, description: "Primary launcher" },
        { source: "app_launcher", target: "main_app", value: 8, description: "Launches main application" },
        { source: "app_launcher", target: "3d_editor", value: 7, description: "Launches 3D editor" },
        { source: "app_launcher", target: "customer_service", value: 7, description: "Launches customer service" },
        { source: "app_launcher", target: "dlw_chat", value: 7, description: "Launches DLW chat" },
        { source: "app_launcher", target: "hunyuan_chat", value: 7, description: "Launches Hunyuan chat" },
        { source: "app_launcher", target: "cc3_curve", value: 7, description: "Launches CC3 curve tool" },
        { source: "app_launcher", target: "cc_converter", value: 6, description: "Launches CC converter" },
        { source: "app_launcher", target: "height_converter", value: 6, description: "Launches height converter" },
        { source: "app_launcher", target: "dose_export", value: 6, description: "Launches dose export tool" },
        { source: "app_launcher", target: "cc_ai_assistant", value: 6, description: "Launches CC AI assistant" },
        { source: "app_launcher", target: "tiktoken_service", value: 5, description: "Launches tokenization service" },
        
        // Main application relationships (based on main.py)
        { source: "main_app", target: "lithography_simulator", value: 9, description: "Lithography simulation" },
        { source: "main_app", target: "photoresist_db", value: 8, description: "Photoresist properties" },
        { source: "main_app", target: "3d_coordinate_height", value: 7, description: "Height profile generation" },
        { source: "main_app", target: "export_files", value: 6, description: "File export" },
        { source: "main_app", target: "input_files", value: 6, description: "File import" },
        
        // 3D editor system relationships (based on interactive_3d_editor.py)
        { source: "3d_editor", target: "main_app", value: 7, description: "Main app integration" },
        { source: "3d_editor", target: "3d_coordinate_height", value: 9, description: "Height profile input" },
        { source: "3d_editor", target: "export_files", value: 6, description: "3D model export" },
        { source: "3d_coordinate_height", target: "export_files", value: 7, description: "Height map output" },
        { source: "3d_coordinate_height", target: "opc", value: 6, description: "OPC input data" },
        
        // Shape analysis relationships (based on shape_analysis.py)
        { source: "shape_analysis", target: "main_app", value: 7, description: "Main app integration" },
        { source: "shape_analysis", target: "3d_editor", value: 8, description: "3D editor analysis" },
        { source: "shape_analysis", target: "3d_coordinate_height", value: 7, description: "Height profile analysis" },
        { source: "shape_analysis", target: "pydlw", value: 6, description: "Core library usage" },
        
        // AI system relationships
        { source: "dlw_chat", target: "deepseek_chat", value: 8, description: "DeepSeek implementation" },
        { source: "hunyuan_chat", target: "tensor2tensor", value: 7, description: "ML model foundation" },
        { source: "dlw_chat", target: "tiktoken_service", value: 6, description: "Token processing" },
        { source: "dlw_chat", target: "ai_knowledge_base", value: 8, description: "Knowledge retrieval" },
        { source: "hunyuan_chat", target: "ai_knowledge_base", value: 8, description: "Knowledge retrieval" },
        
        // CC optimization tools relationships
        { source: "cc_converter", target: "cc3_curve", value: 8, description: "Curve conversion" },
        { source: "height_converter", target: "3d_coordinate_height", value: 8, description: "Height data conversion" },
        { source: "cc_ai_assistant", target: "cc3_curve", value: 9, description: "Curve optimization AI" },
        { source: "dose_export", target: "cc_converter", value: 7, description: "Dose data export" },
        { source: "cc_converter", target: "input_files", value: 5, description: "Input processing" },
        { source: "cc_converter", target: "export_files", value: 5, description: "Output generation" },
        { source: "height_converter", target: "input_files", value: 5, description: "Input processing" },
        { source: "height_converter", target: "export_files", value: 5, description: "Output generation" },
        
        // Core library relationships (based on pydlw)
        { source: "pydlw", target: "lithography_simulator", value: 9, description: "Simulation algorithms" },
        { source: "pydlw", target: "laser_controller", value: 7, description: "Laser control" },
        { source: "pydlw", target: "photoresist_db", value: 8, description: "Material properties" },
        
        // Simulation system relationships
        { source: "simulation", target: "laser_controller", value: 7, description: "Hardware control" },
        { source: "simulation", target: "lithography_simulator", value: 9, description: "Detailed simulation" },
        { source: "simulation", target: "simulation_predictor", value: 8, description: "AI prediction" },
        { source: "simulation_predictor", target: "tensor2tensor", value: 7, description: "ML model integration" },
        
        // OPC system relationships
        { source: "opc", target: "mask_generator", value: 8, description: "Mask generation" },
        { source: "opc", target: "3d_coordinate_height", value: 7, description: "Height profile usage" },
        { source: "opc", target: "parameter_optimizer", value: 8, description: "Parameter optimization" },
        { source: "parameter_optimizer", target: "tensor2tensor", value: 6, description: "ML optimization" },
        { source: "mask_generator", target: "tensor2tensor", value: 6, description: "ML generation" },
        
        // System tools relationships
        { source: "system_monitor", target: "error_reporter", value: 7, description: "Error detection" },
        { source: "system_monitor", target: "dashboard", value: 8, description: "Performance monitoring" },
        { source: "error_reporter", target: "customer_service", value: 8, description: "Support ticket creation" },
        
        // Visualization relationships
        { source: "3d_visualization", target: "3d_editor", value: 9, description: "Interactive visualization" },
        { source: "3d_visualization", target: "shape_analysis", value: 7, description: "Analysis visualization" },
        { source: "3d_visualization", target: "3d_coordinate_height", value: 8, description: "Height visualization" }
    ]
};

// Node color mapping for sphere size
const sphereSizeColorMap = {
    large: '#ff6b00',
    medium: '#0072ce',
    small: '#71cb2d'
};

// Node color mapping for sphere type
const sphereTypeColorMap = {
    simulation: '#ff5722',
    opc: '#2196f3',
    coordinates: '#9c27b0',
    app_service: '#4caf50',
    cc_optimization: '#ff9800',
    tools: '#03a9f4'
};

// Original node color mapping (keeping for backward compatibility)
const nodeColorMap = {
    core: '#0072ce',
    analysis: '#ff6b00',
    simulation: '#00a3e0',
    service: '#c7008e',
    auxiliary: '#71cb2d',
    ai: '#9c27b0'  // 紫色用于AI工具组
};

// Node category icon mapping
const nodeCategoryIconMap = {
    application: 'https://img.icons8.com/color/48/000000/application-window.png',
    module: 'https://img.icons8.com/color/48/000000/module.png',
    library: 'https://img.icons8.com/color/48/000000/book-stack.png',
    tool: 'https://img.icons8.com/color/48/000000/wrench.png',
    service: 'https://img.icons8.com/color/48/000000/online-support.png',
    interface: 'https://img.icons8.com/color/48/000000/monitor.png',
    data: 'https://img.icons8.com/color/48/000000/data-sheet.png',
    ai: 'https://img.icons8.com/color/48/000000/artificial-intelligence.png',
    hardware: 'https://img.icons8.com/color/48/000000/motherboard.png'
}; 