// System component relationship data
const graphData = {
    nodes: [
        // Core components
        { id: "main_app", name: "Main Application", group: "core", category: "application", size: 40, description: "Core interface of DLW application providing DLW simulation, OPC optimization and mask generation" },
        { id: "pydlw", name: "PYDLW Core Library", group: "core", category: "library", size: 22, description: "Provides core algorithm implementation for DLW simulation, including mask generation and dose calculation" },
        
        // 3D editing and analysis
        { id: "3d_editor", name: "Interactive 3D Editor", group: "analysis", category: "application", size: 24, description: "Interactive editing and visualization tool for 3D models, supporting point cloud operations and shape creation" },
        { id: "shape_analysis", name: "Shape Analysis", group: "analysis", category: "application", size: 20, description: "Point cloud analysis, surface fitting and geometric property analysis tools" },
        { id: "shape_designer", name: "Shape Designer", group: "analysis", category: "application", size: 18, description: "Professional shape design tool supporting various geometric shape creation" },
        
        // Data conversion tools
        { id: "data_converter", name: "Data Converter", group: "auxiliary", category: "tool", size: 18, description: "Contrast curve and height file data conversion tool" },
        { id: "cc_converter", name: "CC Curve Converter", group: "auxiliary", category: "tool", size: 15, description: "Tool specifically for converting contrast curve data" },
        { id: "height_converter", name: "Height File Converter", group: "auxiliary", category: "tool", size: 15, description: "Tool specifically for converting height file data" },
        
        // Service systems
        { id: "customer_service", name: "Customer Service System", group: "service", category: "service", size: 20, description: "User support and problem-solving system" },
        { id: "dlw_chat", name: "DLW Chat Assistant", group: "ai", category: "ai", size: 18, description: "Built-in AI assistant providing technical support" },
        { id: "hunyuan_chat", name: "Hunyuan LLM", group: "ai", category: "ai", size: 16, description: "Advanced AI assistant based on Hunyuan large language model" },
        
        // Simulation features
        { id: "simulation", name: "DLW Simulation Module", group: "simulation", category: "module", size: 22, description: "Direct Laser Writing simulation function module" },
        { id: "opc", name: "OPC Optimization Module", group: "simulation", category: "module", size: 22, description: "Optical Proximity Correction optimization function module" },
        { id: "opc_progress", name: "OPC Progress Window", group: "simulation", category: "interface", size: 15, description: "OPC processing progress monitoring interface" },
        
        // Data input/output
        { id: "input_files", name: "Input Files", group: "auxiliary", category: "data", size: 15, description: "Input data files processed by the system, including masks, contrast curves, etc." },
        { id: "export_files", name: "Export Files", group: "auxiliary", category: "data", size: 15, description: "Output data files generated by the system, including optimized masks, shape analysis results, etc." },
        
        // Tools and auxiliary applications
        { id: "cc3_curve", name: "CC3 Curve Comparison Tool", group: "auxiliary", category: "tool", size: 15, description: "Tool for comparing and generating CC3 curves" },
        { id: "dose_export", name: "Dose Export Tool", group: "auxiliary", category: "tool", size: 15, description: "Tool for exporting dose data in CC2 format" },
        
        // AI Components - Extended
        { id: "deepseek_chat", name: "DeepSeek Chat", group: "ai", category: "ai", size: 17, description: "Advanced LLM chat interface based on DeepSeek model for technical consultations" },
        { id: "tiktoken_service", name: "Tokenization Service", group: "ai", category: "ai", size: 14, description: "Token counting and preprocessing service for AI text models" },
        { id: "ai_knowledge_base", name: "AI Knowledge Base", group: "ai", category: "ai", size: 16, description: "Domain-specific knowledge base for AI assistants" },
        
        // Integration Components
        { id: "app_launcher", name: "App Launcher", group: "core", category: "application", size: 18, description: "Central application launcher for all DLW tools" },
        { id: "dlw_launch", name: "DLW Launcher Script", group: "core", category: "tool", size: 14, description: "Script for launching DLW applications with proper environment" },
        
        // Visualization Components
        { id: "3d_visualization", name: "3D Visualization", group: "analysis", category: "module", size: 18, description: "WebGL-based visualization engine for 3D data" },
        { id: "dashboard", name: "System Dashboard", group: "auxiliary", category: "interface", size: 16, description: "Monitoring dashboard for system performance and usage statistics" },
        
        // ML Components
        { id: "shape_prediction", name: "Shape Predictor", group: "ai", category: "ai", size: 16, description: "ML model for predicting optimal shapes based on input parameters" },
        { id: "parameter_optimizer", name: "Parameter Optimizer", group: "ai", category: "ai", size: 17, description: "Neural network-based parameter optimization for DLW process" },
        
        // Support Tools
        { id: "error_reporter", name: "Error Reporter", group: "service", category: "tool", size: 14, description: "Automated error reporting and diagnostic tool" },
        { id: "system_monitor", name: "System Monitor", group: "auxiliary", category: "tool", size: 15, description: "Real-time system resource monitoring tool" },
        
        // New AI Components
        { id: "cc_ai_assistant", name: "CC AI Assistant", group: "ai", category: "ai", size: 16, description: "AI assistant specialized for contrast curve analysis and optimization" },
        { id: "mask_generator", name: "AI Mask Generator", group: "ai", category: "ai", size: 18, description: "Neural network-based mask generation from shape specifications" },
        { id: "laser_calibration", name: "Laser Calibration AI", group: "ai", category: "ai", size: 17, description: "AI-based laser calibration and adjustment system" },
        { id: "simulation_predictor", name: "Simulation Predictor", group: "ai", category: "ai", size: 17, description: "AI model for predicting simulation outcomes before full processing" },
        
        // New DLW-specific components
        { id: "photoresist_db", name: "Photoresist Database", group: "core", category: "data", size: 16, description: "Database of photoresist properties and parameters" },
        { id: "laser_controller", name: "Laser Controller", group: "core", category: "hardware", size: 18, description: "Hardware interface for controlling laser systems" },
        { id: "lithography_simulator", name: "Lithography Simulator", group: "simulation", category: "module", size: 20, description: "Detailed simulator for lithography processes and outcomes" }
    ],
    links: [
        // Core application relationships - primary structure
        { source: "main_app", target: "pydlw", value: 12, description: "Core dependency" },
        { source: "main_app", target: "simulation", value: 10, description: "Feature integration" },
        { source: "main_app", target: "opc", value: 10, description: "Feature integration" },
        { source: "main_app", target: "3d_editor", value: 8, description: "Integrated tool" },
        { source: "main_app", target: "shape_analysis", value: 7, description: "Analysis integration" },
        { source: "main_app", target: "customer_service", value: 5, description: "Support integration" },
        { source: "main_app", target: "app_launcher", value: 9, description: "Launch dependency" },
        
        // 3D editing and analysis relationships
        { source: "3d_editor", target: "shape_analysis", value: 9, description: "Shared analysis" },
        { source: "3d_editor", target: "shape_designer", value: 8, description: "Design integration" },
        { source: "shape_analysis", target: "export_files", value: 6, description: "Analysis output" },
        { source: "shape_designer", target: "3d_editor", value: 7, description: "Shape output" },
        { source: "3d_editor", target: "3d_visualization", value: 9, description: "Visualization engine" },
        { source: "shape_analysis", target: "shape_prediction", value: 6, description: "ML prediction" },
        
        // Simulation feature relationships - core functionality
        { source: "simulation", target: "pydlw", value: 11, description: "Algorithm implementation" },
        { source: "opc", target: "pydlw", value: 11, description: "Algorithm implementation" },
        { source: "opc", target: "opc_progress", value: 7, description: "Progress monitoring" },
        { source: "simulation", target: "export_files", value: 6, description: "Simulation output" },
        { source: "opc", target: "export_files", value: 6, description: "Optimization output" },
        { source: "simulation", target: "parameter_optimizer", value: 8, description: "Parameter optimization" },
        
        // Data conversion relationships
        { source: "data_converter", target: "cc_converter", value: 8, description: "Component relationship" },
        { source: "data_converter", target: "height_converter", value: 8, description: "Component relationship" },
        { source: "cc_converter", target: "input_files", value: 5, description: "Data input" },
        { source: "height_converter", target: "input_files", value: 5, description: "Data input" },
        { source: "cc_converter", target: "export_files", value: 5, description: "Data output" },
        { source: "height_converter", target: "export_files", value: 5, description: "Data output" },
        
        // Service system relationships
        { source: "customer_service", target: "dlw_chat", value: 7, description: "Integrated assistant" },
        { source: "customer_service", target: "hunyuan_chat", value: 6, description: "Integrated AI" },
        { source: "dlw_chat", target: "hunyuan_chat", value: 4, description: "AI integration" },
        { source: "customer_service", target: "error_reporter", value: 6, description: "Error handling" },
        { source: "customer_service", target: "deepseek_chat", value: 7, description: "Advanced AI support" },
        { source: "deepseek_chat", target: "tiktoken_service", value: 5, description: "Token processing" },
        { source: "hunyuan_chat", target: "tiktoken_service", value: 5, description: "Token processing" },
        { source: "dlw_chat", target: "ai_knowledge_base", value: 8, description: "Domain knowledge" },
        { source: "deepseek_chat", target: "ai_knowledge_base", value: 8, description: "Domain knowledge" },
        { source: "hunyuan_chat", target: "ai_knowledge_base", value: 7, description: "Domain knowledge" },
        
        // File tool relationships
        { source: "cc3_curve", target: "export_files", value: 5, description: "Curve output" },
        { source: "dose_export", target: "export_files", value: 5, description: "Dose data output" },
        { source: "input_files", target: "main_app", value: 7, description: "Application input" },
        { source: "input_files", target: "simulation", value: 8, description: "Simulation input" },
        { source: "input_files", target: "opc", value: 8, description: "Optimization input" },
        
        // Cross-module relationships
        { source: "main_app", target: "data_converter", value: 5, description: "Data processing" },
        { source: "main_app", target: "cc3_curve", value: 4, description: "Curve generation" },
        { source: "main_app", target: "dose_export", value: 4, description: "Dose output" },
        { source: "opc", target: "data_converter", value: 3, description: "Data conversion" },
        { source: "3d_editor", target: "export_files", value: 5, description: "3D model output" },
        { source: "shape_designer", target: "export_files", value: 5, description: "Shape output" },
        
        // Auxiliary application relationships
        { source: "cc3_curve", target: "cc_converter", value: 4, description: "Data processing" },
        { source: "dose_export", target: "simulation", value: 4, description: "Simulation output" },
        { source: "data_converter", target: "main_app", value: 3, description: "Data provision" },
        { source: "data_converter", target: "3d_editor", value: 3, description: "3D data input" },
        
        // Additional core workflow links
        { source: "pydlw", target: "simulation", value: 9, description: "Simulation algorithms" },
        { source: "pydlw", target: "opc", value: 9, description: "Optimization algorithms" },
        { source: "simulation", target: "opc", value: 8, description: "Process pipeline" },
        { source: "shape_analysis", target: "shape_designer", value: 6, description: "Analysis feedback" },
        { source: "export_files", target: "shape_analysis", value: 4, description: "Analysis input" },
        
        // Launcher and integration relationships
        { source: "app_launcher", target: "dlw_launch", value: 8, description: "Launch script" },
        { source: "app_launcher", target: "3d_editor", value: 6, description: "App launching" },
        { source: "app_launcher", target: "shape_designer", value: 6, description: "App launching" },
        { source: "app_launcher", target: "data_converter", value: 5, description: "App launching" },
        { source: "app_launcher", target: "system_monitor", value: 4, description: "System monitoring" },
        { source: "dlw_launch", target: "main_app", value: 7, description: "Main app launch" },
        
        // AI and ML relationships
        { source: "shape_prediction", target: "shape_analysis", value: 7, description: "Analysis input" },
        { source: "parameter_optimizer", target: "opc", value: 7, description: "OPC optimization" },
        { source: "main_app", target: "dlw_chat", value: 6, description: "Integrated support" },
        { source: "error_reporter", target: "ai_knowledge_base", value: 5, description: "Error knowledge" },
        
        // Monitoring and visualization
        { source: "system_monitor", target: "dashboard", value: 7, description: "Performance data" },
        { source: "main_app", target: "dashboard", value: 5, description: "Usage statistics" },
        { source: "3d_visualization", target: "dashboard", value: 4, description: "Visualization component" },
        { source: "3d_visualization", target: "3d_editor", value: 8, description: "Visualization engine" },
        { source: "shape_prediction", target: "3d_visualization", value: 6, description: "Prediction visualization" },
        
        // Error handling
        { source: "error_reporter", target: "customer_service", value: 7, description: "Support ticket creation" },
        { source: "main_app", target: "error_reporter", value: 6, description: "Error reporting" },
        { source: "simulation", target: "error_reporter", value: 5, description: "Simulation errors" },
        { source: "opc", target: "error_reporter", value: 5, description: "OPC errors" },
        { source: "system_monitor", target: "error_reporter", value: 6, description: "System issue detection" },
        
        // New AI tool relationships
        { source: "cc_ai_assistant", target: "cc_converter", value: 7, description: "CC data processing" },
        { source: "cc_ai_assistant", target: "ai_knowledge_base", value: 6, description: "Knowledge retrieval" },
        { source: "cc_ai_assistant", target: "cc3_curve", value: 8, description: "Curve optimization" },
        { source: "mask_generator", target: "shape_designer", value: 7, description: "Shape integration" },
        { source: "mask_generator", target: "simulation", value: 8, description: "Simulation input" },
        { source: "mask_generator", target: "shape_prediction", value: 6, description: "ML feedback" },
        { source: "laser_calibration", target: "laser_controller", value: 7, description: "Hardware control" },
        { source: "laser_calibration", target: "parameter_optimizer", value: 6, description: "Parameter tuning" },
        { source: "simulation_predictor", target: "simulation", value: 9, description: "Simulation acceleration" },
        { source: "simulation_predictor", target: "opc", value: 7, description: "OPC pre-processing" },
        { source: "main_app", target: "cc_ai_assistant", value: 5, description: "AI assistant integration" },
        { source: "main_app", target: "mask_generator", value: 6, description: "Mask creation" },
        
        // New DLW component relationships
        { source: "photoresist_db", target: "simulation", value: 8, description: "Simulation parameters" },
        { source: "photoresist_db", target: "opc", value: 7, description: "Optimization parameters" },
        { source: "photoresist_db", target: "pydlw", value: 6, description: "Core data" },
        { source: "laser_controller", target: "main_app", value: 7, description: "Hardware control" },
        { source: "laser_controller", target: "simulation", value: 6, description: "Simulation parameters" },
        { source: "lithography_simulator", target: "simulation", value: 8, description: "Enhanced simulation" },
        { source: "lithography_simulator", target: "parameter_optimizer", value: 7, description: "Parameter input" },
        { source: "lithography_simulator", target: "photoresist_db", value: 6, description: "Material properties" }
    ]
};

// Node color mapping
const nodeColorMap = {
    core: '#0072ce',
    analysis: '#ff6b00',
    simulation: '#00a3e0',
    service: '#c7008e',
    auxiliary: '#71cb2d',
    ai: '#9c27b0'  // 紫色用于AI工具组
};

// Node category icon mapping
const nodeCategoryIconMap = {
    application: 'https://img.icons8.com/color/48/000000/application-window.png',
    module: 'https://img.icons8.com/color/48/000000/module.png',
    library: 'https://img.icons8.com/color/48/000000/book-stack.png',
    tool: 'https://img.icons8.com/color/48/000000/wrench.png',
    service: 'https://img.icons8.com/color/48/000000/online-support.png',
    interface: 'https://img.icons8.com/color/48/000000/monitor.png',
    data: 'https://img.icons8.com/color/48/000000/data-sheet.png',
    ai: 'https://img.icons8.com/color/48/000000/artificial-intelligence.png',
    hardware: 'https://img.icons8.com/color/48/000000/motherboard.png'
}; 